version: "3.9"

services:
  server:
    build:
      context: ./PBL_REDES_1
      dockerfile: Dockerfile-server
    container_name: backend-tcp
    ports:
      - "8888:8888"
    networks:
      - app-network
    volumes:
      - dados-volume:/app/server/data
    stdin_open: true
    tty: true

  frontend-react:
    build: ./ev-routing-app
    ports:
      - "5173:5173"
      - "4000:4000"
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  dados-volume:
