export const SOCKET_EVENTS = {
  INIT: 'INICIANDO',
  CARS: 'cars',
  USER_SELECTION: 'USER_SELECTION',
  START_ROUTE: 'INICIAR_TRAJETO',
  BATTERY_UPDATE: 'BATTERY_UPDATE',
  BATTERY_WARNING: 'BATTERY_WARNING',
  BATTERY_CRITICAL: 'BATTERY_CRITICAL',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  ARRIVED: 'ARRIVED',
};

export const VITE_USE_MOCK = import.meta.env.VITE_USE_MOCK === 'true';
export const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL ?? '';
